In [9]:
import numpy as np
array = [1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11, 12, 11, 23, 34]
array = np.array(array)
print(array)
print(type(array))

print(np.unique(array))
print(np.min(array))
print(np.max(array))
import cv2
img = cv2.imread('/media/dheeraj/9A26F0CB26F0AA01/WORK/github_repo/Image-segmentation/dataset1/annotations_prepped_test/0016E5_08135.png')
    
print(np.max(img))
print(np.min(img))
print(np.unique(img))

[ 1  1  2  3  4  5  6  7  8  9 10 11 11 12 11 23 34]
<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 23 34]
1
34
11
0
[ 0  1  2  3  4  5  6  7  8  9 10 11]
